# Generated by Django 3.1.7 on 2021-10-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionchoise',
            name='region',
            field=models.CharField(blank=True, default=1, max_length=200, unique=True, verbose_name='Введите регион'),
            preserve_default=False,
        ),
    ]
