# Generated by Django 3.1.7 on 2021-10-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211005_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='A1',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='A1 Число погибших результате ЧС на 100 000 человек'),
        ),
    ]
