# Generated by Django 3.1.7 on 2021-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211026_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='A1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='A1 Число погибших результате ЧС на 100 000 человек'),
        ),
        migrations.AlterField(
            model_name='table',
            name='B1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='B1 Число непосредственно пострадавших в результате ЧС на 100\xa0000 человек'),
        ),
        migrations.AlterField(
            model_name='table',
            name='B2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='B2 Число получивших увечья или пострадавших от болезней в результате ЧС на 100\xa0000 человек'),
        ),
        migrations.AlterField(
            model_name='table',
            name='C1',
            field=models.CharField(max_length=10, null=True, verbose_name='C1 Прямые экономические потери, связанные с бедствиями в отношении мирового валового внутреннего продукта (составной показатель)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='G6a',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='G6a Доля населения, подверженного угрозе или риску ЧС, защита которого обеспечивается путем заблаговременной эвакуации на основе раннего оповещения'),
        ),
        migrations.AlterField(
            model_name='table',
            name='G6a1',
            field=models.IntegerField(blank=True, null=True, verbose_name='G6a1 Число людей, защита которого обеспечивается путем заблаговременной эвакуации на основе экстренного оповещения'),
        ),
    ]
