# Generated by Django 3.1.7 on 2021-10-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211026_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='G3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='G3 Число людей охваченных информационной системой раннего оповещения через местные органы власти или через национальные механизмы распространения информации на 100 000 человек'),
        ),
    ]
