# Generated by Django 3.1.7 on 2021-10-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211026_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='C1',
            field=models.CharField(max_length=10000000, null=True, verbose_name='C1 Прямые экономические потери, связанные с бедствиями в отношении мирового валового внутреннего продукта (составной показатель)'),
        ),
    ]
