# Generated by Django 3.1.7 on 2021-10-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211026_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdate',
            name='vrp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Введите ВВР'),
        ),
    ]
