# Generated by Django 3.1.7 on 2021-10-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211026_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='A3',
            field=models.IntegerField(blank=True, null=True, verbose_name='A2 Число пострадавших в результате ЧС'),
        ),
    ]
